import { useEffect, useState } from 'react'
import { FileText, Download, MessageSquare, CheckCircle } from 'lucide-react'
import { ChartBar, ChartDonut, ChartLine } from '../shared/Chart'

interface ReportViewerProps {
  reportId: string | null
}

const mockData = {
  mcName: 'BMC Mumbai',
  period: 'Week 15 (Apr 10 - Apr 16, 2026)',
  narrative: 'BMC Mumbai demonstrated strong performance overall, resolving 1,240 issues this week. However, there is a growing backlog in Ward K-West (Andheri) primarily due to pre-monsoon roadworks. The resolution rate of 82% is above the SLA, but electrical tasks are lagging (average 12 hours resolution time vs 4 hour SLA). Reallocation of crews from Ward F-South is strictly recommended.',
  volumeData: [
    { name: 'Mon', issues: 180 }, { name: 'Tue', issues: 210 }, { name: 'Wed', issues: 195 },
    { name: 'Thu', issues: 225 }, { name: 'Fri', issues: 240 }, { name: 'Sat', issues: 110 }, { name: 'Sun', issues: 80 }
  ],
  catData: [
    { name: 'Roads', value: 450, color: '#3B82F6' },
    { name: 'Water', value: 310, color: '#06B6D4' },
    { name: 'Electric', value: 250, color: '#F59E0B' },
    { name: 'Sanitation', value: 230, color: '#10B981' }
  ],
  trendData: [
    { name: 'Wk 12', hours: 6.2 }, { name: 'Wk 13', hours: 5.8 }, { name: 'Wk 14', hours: 5.4 }, { name: 'Wk 15', hours: 5.1 }
  ]
}

export default function ReportViewer({ reportId }: ReportViewerProps) {
  const [report, setReport] = useState<any>(mockData)

  useEffect(() => {
    if (reportId) {
      fetch('http://localhost:8000/api/prescient/weekly')
        .then(res => res.json())
        .then(data => {
          if (data.agent === 'PRESCIENT' && data.forecasts && data.forecasts.length > 0) {
            setReport({
              ...mockData,
              mcName: data.forecasts[0].mc,
              narrative: data.forecasts[0].insight,
              period: `Generated: ${new Date().toLocaleDateString()}`
            })
          }
        })
        .catch(console.error)
    }
  }, [reportId])
  if (!reportId) {
    return (
      <div className="h-full flex flex-col items-center justify-center text-text-muted border border-border rounded-2xl bg-surface-elevated">
        <FileText size={48} className="mb-4 opacity-20" />
        <p>Select a report from the inbox to view details.</p>
      </div>
    )
  }

  return (
    <div className="h-full bg-surface-elevated rounded-2xl border border-border flex flex-col overflow-hidden">
      {/* Header */}
      <div className="px-6 py-5 border-b border-border flex items-center justify-between">
        <div>
          <h2 className="text-xl font-bold text-text-primary font-display">{report.mcName} — Weekly Performance</h2>
          <p className="text-sm text-text-secondary mt-1">{report.period} • Generated by PRESCIENT</p>
        </div>
        <div className="flex gap-2">
          <button className="p-2 rounded-lg border border-border text-text-secondary hover:text-text-primary hover:bg-surface-hover transition-colors">
            <Download size={18} />
          </button>
          <button className="px-4 py-2 rounded-lg bg-surface border border-border text-text-primary text-sm font-medium hover:bg-surface-hover transition-colors flex items-center gap-2">
             <MessageSquare size={16} /> Send Feedback
          </button>
          <button className="px-4 py-2 rounded-lg bg-agent-guardian text-white text-sm font-medium hover:opacity-90 transition-opacity flex items-center gap-2">
             <CheckCircle size={16} /> Mark Reviewed
          </button>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto p-6">
        <section className="mb-8">
          <h3 className="text-sm font-semibold text-text-primary mb-3 text-agent-prescient">PRESCIENT Executive Summary</h3>
          <p className="text-sm leading-relaxed text-text-secondary bg-surface p-4 rounded-xl border border-border">
            {report.narrative}
          </p>
        </section>

        <section className="grid grid-cols-2 gap-6 mb-8">
          <div className="p-4 rounded-xl border border-border bg-surface">
             <h3 className="text-sm font-semibold text-text-primary mb-4">Daily Issue Volume</h3>
             <ChartBar data={mockData.volumeData} dataKey="issues" color="#3B82F6" height={180} />
          </div>
          <div className="p-4 rounded-xl border border-border bg-surface">
             <h3 className="text-sm font-semibold text-text-primary mb-4">Category Distribution</h3>
             <ChartDonut data={mockData.catData} height={180} />
          </div>
        </section>

        <section className="grid grid-cols-2 gap-6">
          <div className="p-4 rounded-xl border border-border bg-surface">
             <h3 className="text-sm font-semibold text-text-primary mb-4">Avg Resolution Time (Week over Week)</h3>
             <ChartLine data={mockData.trendData} lines={[{ dataKey: 'hours', color: '#10B981' }]} height={180} />
          </div>
          <div className="p-4 rounded-xl border border-border bg-surface">
             <h3 className="text-sm font-semibold text-text-primary mb-4">Fund Utilisation</h3>
             <div className="mb-2 flex justify-between text-sm">
                <span className="text-text-secondary">Q1 Budget Spent</span>
                <span className="text-text-primary font-bold">₹42 Cr / ₹55 Cr</span>
             </div>
             <div className="w-full h-3 rounded-full bg-surface-elevated border border-border overflow-hidden">
                <div className="h-full bg-blue-500 rounded-full" style={{ width: '76%' }} />
             </div>
             <p className="text-xs text-text-muted mt-2 text-right">76% Utilised</p>

             <h3 className="text-sm font-semibold text-text-primary mt-6 mb-3">Top Escalations</h3>
             <ul className="text-xs text-text-secondary space-y-2">
                <li>• Water main break (FC Road) — 4h overdue</li>
                <li>• Bridge structural crack (Katraj) — High hazard</li>
             </ul>
          </div>
        </section>
      </div>
    </div>
  )
}
